### ISSUE TITLE
Choose wheel result

### ISSUE THREAD

**Issue by ThomyLorenzatti** [nitocode/vue3-roulette#1]
Hi ! I want to know if it's possible to choose (before launching wheel) the result.

And how ?

**Comment by nitocode** [comment]
Hi @ThomyLorenzatti 

This is indeed a nice idea. I just added a property `wheel-result-index` to do that. 

Here is an example 

```html
<Roulette ref="wheel" :items="items" :wheel-result-index="{ value: 6 }" @click="launchWheel" />
```

Here are the details of the new release [v0.3.0](https://github.com/nitocode/vue3-roulette/releases/tag/v0.3.0)

As you can see I don't work often on this project anymore. Don't hesitate to suggest other enhancement.

Regards,
